name: Cache Node and NPM Dependencies
description: "This action allows to cache both Node and NPM dependencies based on the package-lock.json file."
inputs: 
  node-version:
    description: "nodejs version"
    default: 20.x
    required: true
  working-dir:
    required: false
    description: "working dir"
    default: .


runs: 
  using: composite
  steps:
    - name: setup version ${{inputs.node-version}}
      uses: actions/setup-node@v4
      with: 
        node-version: ${{inputs.node-version}}
    - name: cache dep
      id: cache
      uses: actions/cache@v3
      with: 
        path: ${{inputs.working-dir}}/node_modules
        key: deps-node-modules-${{ hashFiles(format('{0}/{1}', inputs.working-dir, 'package-lock.json')) }}.
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci
      shell: bash
      working-directory: ${{ inputs.working-dir }}