name: 06 - Contexts
run-name: 06 - Contexts | DEBUG - ${{ inputs.debug }}
on: 
    push: 
    workflow_dispatch:
        inputs:
            debug:
                type: boolean
                default: false

env:
    MY_WORKFLOW_VAR: 'workflow'
    MY_OVERWRITTEN_VAR: 'workflow'


jobs:
    echo-data:
        env: 
            MY_JOB_VAR: 'job'
            MY_OVERWRITTEN_VAR: 'job'
        runs-on: ubuntu-latest
        steps:
            - run: |
                echo "Ev name: ${{github.event_name}}"
                echo "ref: ${{github.ref}}"
                echo "sha: ${{github.sha}}"
                echo "actor: ${{github.actor}}"
                echo "workflow: ${{github.workflow}}"
                echo "run id: ${{github.run_id}}"
                echo "run number: ${{github.run_number}}"
            - name: Retrieve Variable
              run: echo "${{vars.REPO_VAR}}"
            - name: print env
              env:
                MY_OVERWRITTEN_VAR: 'step'
              run: |
                echo "Workflow env: ${{ env.MY_WORKFLOW_VAR }}"
                echo "Overwritten env: ${{ env.MY_OVERWRITTEN_VAR }}"
            - name: Print Env Variables
              run: |
                echo "Workflow env: ${{ env.MY_WORKFLOW_VAR }}"
                echo "Overwritten env: ${{ env.MY_OVERWRITTEN_VAR }}"