name: 09 - using functions
on: 
    push:
    workflow_dispatch:

jobs:
    echo1:
        runs-on: ubuntu-latest
        steps:
            - run: sleep 20
            - run: exit -1
            - if: ${{ success() }}
              run: echo "I will print if previous steps succeed"
            - if: ${{ failure() }}
              run: echo "I will run if previous fail"
            - if: ${{ !cancelled() }}
              run: echo "not cancelled"
            - if: ${{ cancelled() }}
              run: echo "Ws cancelled"
