name: 11 - inputs
on: 
    workflow_dispatch:
        inputs:
            dry-run:
                type: boolean
                default: false
                description: "skip deploymenet and only print build output"
            target:
                type: environment
                description: "Which enviroment the workflow will target"
            tag:
                type: choice
                options:
                  - v1
                  - v2
                  - v3
                default: v3
                description: Release from which to build and deploy


jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: build
              run: echo "Building from tag ${{inputs.tag}}"

    deploy:
        runs-on: ubuntu-latest
        if: ${{!inputs.dry-run}}
        needs: build
        environment: ${{inputs.target}}
        steps:
            - name: Deploy
              run: echo "deploying to ${{inputs.target}}"